" set antialias                     " MacVim: smooth fonts.
" set encoding=utf-8                " Use UTF-8 everywhere.
" set guioptions-=T                 " Hide toolbar.
" 
" set guioptions-=r                 " Don't show right scrollbar
" 
" set guifont=:h12
" set bg=dark
" set fuopt+=maxhorz " grow to maximum horizontal width on entering fullscreen mode
" set go-=L"
